# Generated by Django 5.0.4 on 2025-01-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
