# Generated by Django 5.0.4 on 2025-01-15 18:51

from django.db import migrations

from main_app.models import StudentEnrollment


def migrate_m2m_to_through(apps, schema_editor):
    Student = apps.get_model('main_app', 'Student')
    StudentSubject = apps.get_model('main_app', 'StudentEnrollment')

    # Transfer data from `subjects_old` to the `StudentEnrollment` table
    for student in Student.objects.all():
        for subject in student.subjects_old.all():
            StudentSubject.objects.create(student=student, subject=subject)

class Migration(migrations.Migration):



    dependencies = [
        ('main_app', '0004_studentenrollment_student_subjects'),
    ]

    operations = [
        migrations.RunPython(migrate_m2m_to_through),
    ]
