# Generated by Django 5.0.4 on 2025-01-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_driver_drivinglicence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrivingLicence',
            new_name='DrivingLicense',
        ),
    ]
