# Generated by Django 5.0.4 on 2025-01-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_eventregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventregistration',
            old_name='participants_name',
            new_name='participant_name',
        ),
    ]
