# Generated by Django 5.0.4 on 2025-01-09 08:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_participants_name_eventregistration_participant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
