# Generated by Django 5.0.4 on 2025-01-09 13:00

from django.db import migrations

def define_price(apps, schema_editor):

    smartphone_model = apps.get_model('main_app', 'Smartphone')
    items = smartphone_model.objects.all()

    for item in items:
        item.price = len(item.brand) * 120

    smartphone_model.objects.bulk_update(items, ['price'])

def reverse_price_default(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    items = smartphone_model.objects.all()

    for item in items:
        item.price = smartphone_model._meta.get_field('price').default

    smartphone_model.objects.bulk_update(items, ['price'])

def define_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    items = smartphone_model.objects.all()

    for item in items:
        if item.price < 750:
            item.category = 'Cheap'
        else:
            item.category = 'Expensive'

    smartphone_model.objects.bulk_update(items, ['category'])

def reverse_category_default(apps, schema_editor):

    smartphone_model = apps.get_model('main_app', 'Smartphone')
    items = smartphone_model.objects.all()

    for item in items:
        item.category = smartphone_model._meta.get_field('category').default

    smartphone_model.objects.bulk_update(items, ['category'])



class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_smartphone'),
    ]

    operations = [
        migrations.RunPython(define_price, reverse_price_default),
        migrations.RunPython(define_category, reverse_category_default)
    ]
