# Generated by Django 5.0.4 on 2025-01-09 19:29
from contextlib import nullcontext
from datetime import timedelta
from turtledemo.clock import setup

from django.db import migrations




def process_order(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')
    items = order_model.objects.all()

    for item in items:
        if item.status == 'Pe':
            item.delivery = item.order_date + timedelta(days=3)
            item.save()
        elif item.status == 'Co':
            item.warranty = '24 months'
            item.save()
        elif item.status == 'Ca':
            item.delete()


def set_defaults(apps, schema_editor):

    order_model = apps.get_model('main_app', 'Order')
    items = order_model.objects.all()

    for item in items:
        if item.status == 'Pe':
            item.delivery = None
        elif item.status == 'Co':
            item.warranty = order_model._meta.get_field('warranty').default
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_order'),
    ]

    operations = [
        migrations.RunPython(process_order, set_defaults)
    ]
